"""create initial click nfe schema

Revision ID: 8c964dc2a0e2
Revises: 
Create Date: 2026-09-15 16:58:22.029029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c964dc2a0e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscal_countries',
    sa.Column('bacen_code', sa.String(length=4), nullable=False),
    sa.Column('iso_alpha_2', sa.String(length=2), nullable=True),
    sa.Column('iso_alpha_3', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('bacen_code')
    )
    with op.batch_alter_table('fiscal_countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fiscal_countries_active'), ['active'], unique=False)
        batch_op.create_index('ix_fiscal_countries_active_validity', ['active', 'valid_from', 'valid_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_countries_iso_alpha_2'), ['iso_alpha_2'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_countries_iso_alpha_3'), ['iso_alpha_3'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_countries_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_countries_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_countries_valid_until'), ['valid_until'], unique=False)

    op.create_table('fiscal_municipalities',
    sa.Column('code', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('fiscal_municipalities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fiscal_municipalities_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_municipalities_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_municipalities_state'), ['state'], unique=False)
        batch_op.create_index('ix_fiscal_municipalities_state_name', ['state', 'name'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=64), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_nome'), ['nome'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_resumido', sa.String(length=255), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=64), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=64), nullable=True),
    sa.Column('endereco_completo_escritorio', sa.Text(), nullable=True),
    sa.Column('endereco_completo_armazem', sa.Text(), nullable=True),
    sa.Column('cnae_principal', sa.Text(), nullable=True),
    sa.Column('cnae_secundario', sa.Text(), nullable=True),
    sa.Column('regime_tributacao', sa.String(length=32), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'cnpj', name='uq_clients_org_cnpj')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_cnpj'), ['cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_razao_social'), ['razao_social'], unique=False)

    op.create_table('nfe_carriers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=60), nullable=False),
    sa.Column('trade_name', sa.String(length=60), nullable=True),
    sa.Column('tax_id', sa.String(length=14), nullable=False),
    sa.Column('state_registration', sa.String(length=30), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=60), nullable=False),
    sa.Column('complement', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('municipality_code', sa.String(length=7), nullable=False),
    sa.Column('municipality_name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=8), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'tax_id', name='uq_nfe_carriers_org_tax_id')
    )
    with op.batch_alter_table('nfe_carriers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfe_carriers_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_carriers_legal_name'), ['legal_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_carriers_municipality_code'), ['municipality_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_carriers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_carriers_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_carriers_tax_id'), ['tax_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_carriers_trade_name'), ['trade_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('setor', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('admin_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('can_manage_users', sa.Boolean(), nullable=False),
    sa.Column('can_manage_settings', sa.Boolean(), nullable=False),
    sa.Column('can_manage_billing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('client_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=64), nullable=True),
    sa.Column('whatsapp', sa.String(length=64), nullable=True),
    sa.Column('cargo_departamento', sa.String(length=255), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_contacts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_contacts_email'), ['email'], unique=False)

    op.create_table('client_fiscal_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('state_registration', sa.String(length=30), nullable=True),
    sa.Column('tax_regime', sa.String(length=1), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=60), nullable=False),
    sa.Column('complement', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('city_code', sa.String(length=7), nullable=False),
    sa.Column('city_name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=8), nullable=False),
    sa.Column('country_code', sa.String(length=4), nullable=False),
    sa.Column('country_name', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'client_id', 'is_default', name='uq_client_fiscal_profile_default')
    )
    with op.batch_alter_table('client_fiscal_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_fiscal_profiles_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_fiscal_profiles_organization_id'), ['organization_id'], unique=False)

    op.create_table('client_import_tax_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('issuer_state', sa.String(length=2), nullable=False),
    sa.Column('import_purpose', sa.String(length=30), nullable=False),
    sa.Column('import_modality', sa.String(length=30), nullable=True),
    sa.Column('tax_regime', sa.String(length=2), nullable=True),
    sa.Column('ncm_pattern', sa.String(length=8), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=False),
    sa.Column('additional_cost_defaults', sa.JSON(), nullable=True),
    sa.Column('transport_defaults', sa.JSON(), nullable=True),
    sa.Column('payment_defaults', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_import_tax_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_import_tax_rules_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_import_tax_rules_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_import_tax_rules_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_import_tax_rules_import_modality'), ['import_modality'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_import_tax_rules_import_purpose'), ['import_purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_import_tax_rules_issuer_state'), ['issuer_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_import_tax_rules_ncm_pattern'), ['ncm_pattern'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_import_tax_rules_organization_id'), ['organization_id'], unique=False)

    op.create_table('external_provider_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('importer_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('portal_unico', 'serpro', 'gett', 'sefaz', 'private_fiscal_api', name='external_provider', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('environment', sa.Enum('homologation', 'production', name='fiscal_environment', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('auth_type', sa.Enum('certificate', 'oauth', 'api_key', 'certificate_plus_token', name='external_auth_type', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'expired', 'error', name='external_connection_status', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('credentials_ref', sa.String(length=255), nullable=True),
    sa.Column('last_healthcheck_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['importer_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'importer_id', 'provider', 'environment', name='uq_external_provider_connection_context')
    )
    with op.batch_alter_table('external_provider_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_provider_connections_importer_id'), ['importer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_provider_connections_organization_id'), ['organization_id'], unique=False)

    op.create_table('fiscal_certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.Enum('homologation', 'production', name='fiscal_certificate_environment', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('provider', sa.Enum('gcp_secret_manager', 'gcp_cloud_storage', name='fiscal_credential_provider', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('status', sa.Enum('pending_validation', 'active', 'expired', 'revoked', 'disabled', 'invalid', name='fiscal_certificate_status', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('certificate_ref', sa.String(length=500), nullable=False),
    sa.Column('password_ref', sa.String(length=500), nullable=False),
    sa.Column('issuer_cnpj', sa.String(length=14), nullable=False),
    sa.Column('certificate_fingerprint_sha256', sa.String(length=64), nullable=True),
    sa.Column('certificate_serial_number', sa.String(length=160), nullable=True),
    sa.Column('subject_name', sa.String(length=500), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'certificate_ref', name='uq_fiscal_certificate_org_ref')
    )
    with op.batch_alter_table('fiscal_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fiscal_certificates_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_certificates_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_certificates_issuer_cnpj'), ['issuer_cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_certificates_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiscal_certificates_valid_until'), ['valid_until'], unique=False)

    op.create_table('import_processes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('importer_id', sa.UUID(), nullable=False),
    sa.Column('reference_code', sa.String(length=80), nullable=False),
    sa.Column('duimp_number', sa.String(length=50), nullable=True),
    sa.Column('duimp_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('created', 'duimp_fetching', 'duimp_fetched', 'duimp_fetch_failed', 'duimp_normalized', 'fiscal_draft_created', 'draft_validation_failed', 'draft_ready', 'xml_generated', 'xml_validation_failed', 'xml_validated', 'xml_signed', 'transmission_pending', 'transmitted', 'authorized', 'rejected', 'cancelled', 'failed', name='import_process_status', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('source', sa.Enum('manual', 'portal_unico', 'gett_import', 'api', name='import_process_source', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['importer_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'reference_code', name='uq_import_process_org_reference')
    )
    with op.batch_alter_table('import_processes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_processes_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_processes_duimp_number'), ['duimp_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_processes_importer_id'), ['importer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_processes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_processes_reference_code'), ['reference_code'], unique=False)

    op.create_table('nfe_number_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.Enum('homologation', 'production', name='nfe_number_sequence_environment', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('model', sa.String(length=2), nullable=False),
    sa.Column('series', sa.String(length=10), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.Column('initial_number', sa.Integer(), nullable=False),
    sa.Column('max_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='nfe_number_sequence_status', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('last_reserved_number', sa.Integer(), nullable=True),
    sa.Column('last_reserved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'client_id', 'environment', 'model', 'series', name='uq_nfe_number_sequence_client_env_model_series')
    )
    with op.batch_alter_table('nfe_number_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfe_number_sequences_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_number_sequences_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_number_sequences_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_number_sequences_status'), ['status'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(length=1024), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('duimp_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('import_process_id', sa.UUID(), nullable=False),
    sa.Column('duimp_number', sa.String(length=50), nullable=False),
    sa.Column('duimp_version', sa.String(length=20), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('normalized_payload', sa.JSON(), nullable=True),
    sa.Column('source_provider', sa.Enum('portal_unico', 'serpro', 'gett', 'sefaz', 'private_fiscal_api', name='duimp_snapshot_source_provider', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_process_id'], ['import_processes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duimp_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duimp_snapshots_duimp_number'), ['duimp_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_duimp_snapshots_import_process_id'), ['import_process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duimp_snapshots_organization_id'), ['organization_id'], unique=False)

    op.create_table('external_api_request_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('import_process_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('portal_unico', 'serpro', 'gett', 'sefaz', 'private_fiscal_api', name='external_api_log_provider', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('endpoint_name', sa.String(length=100), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', name='external_api_http_method', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('external_protocol', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_process_id'], ['import_processes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_api_request_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_api_request_logs_import_process_id'), ['import_process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_api_request_logs_organization_id'), ['organization_id'], unique=False)

    op.create_table('nfe_document_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('import_process_id', sa.UUID(), nullable=False),
    sa.Column('duimp_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('allocation_basis', sa.String(length=40), nullable=False),
    sa.Column('shared_costs', sa.JSON(), nullable=False),
    sa.Column('totals', sa.JSON(), nullable=False),
    sa.Column('reconciliation', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['duimp_snapshot_id'], ['duimp_snapshots.id'], ),
    sa.ForeignKeyConstraint(['import_process_id'], ['import_processes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('duimp_snapshot_id', 'version_number', name='uq_nfe_document_plan_snapshot_version')
    )
    with op.batch_alter_table('nfe_document_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfe_document_plans_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_document_plans_duimp_snapshot_id'), ['duimp_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_document_plans_import_process_id'), ['import_process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_document_plans_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_document_plans_status'), ['status'], unique=False)

    op.create_table('nfe_item_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('import_process_id', sa.UUID(), nullable=False),
    sa.Column('duimp_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('duimp_item_number', sa.String(length=30), nullable=False),
    sa.Column('import_purpose', sa.String(length=30), nullable=False),
    sa.Column('tax_rule_id', sa.UUID(), nullable=True),
    sa.Column('cfop', sa.String(length=4), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('classified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classified_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['duimp_snapshot_id'], ['duimp_snapshots.id'], ),
    sa.ForeignKeyConstraint(['import_process_id'], ['import_processes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tax_rule_id'], ['client_import_tax_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('duimp_snapshot_id', 'duimp_item_number', name='uq_nfe_item_classification_snapshot_item')
    )
    with op.batch_alter_table('nfe_item_classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfe_item_classifications_classified_by_user_id'), ['classified_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_item_classifications_duimp_snapshot_id'), ['duimp_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_item_classifications_import_process_id'), ['import_process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_item_classifications_import_purpose'), ['import_purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_item_classifications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_item_classifications_tax_rule_id'), ['tax_rule_id'], unique=False)

    op.create_table('nfe_planned_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_plan_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('exporter_key', sa.String(length=255), nullable=False),
    sa.Column('exporter_code', sa.String(length=100), nullable=True),
    sa.Column('foreign_supplier', sa.JSON(), nullable=True),
    sa.Column('operation_nature', sa.String(length=60), nullable=False),
    sa.Column('item_purposes', sa.JSON(), nullable=False),
    sa.Column('mixed_import_purposes', sa.Boolean(), nullable=False),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.Column('customs_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allocated_shared_costs', sa.JSON(), nullable=False),
    sa.Column('totals', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_plan_id'], ['nfe_document_plans.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_plan_id', 'exporter_key', name='uq_nfe_planned_document_plan_exporter')
    )
    with op.batch_alter_table('nfe_planned_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfe_planned_documents_document_plan_id'), ['document_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_planned_documents_exporter_code'), ['exporter_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_planned_documents_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_planned_documents_status'), ['status'], unique=False)

    op.create_table('nfe_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('import_process_id', sa.UUID(), nullable=False),
    sa.Column('importer_id', sa.UUID(), nullable=False),
    sa.Column('duimp_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('planned_document_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.Enum('55', name='nfe_model', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('purpose', sa.Enum('normal', 'complementary', 'adjustment', 'return', name='nfe_purpose', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('operation_type', sa.Enum('entry', 'exit', name='nfe_operation_type', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('environment', sa.Enum('homologation', 'production', name='nfe_environment', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('series', sa.String(length=10), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'validation_failed', 'ready_for_xml', 'xml_generated', 'signed', 'transmitted', 'authorized', 'rejected', 'cancelled', name='nfe_draft_status', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('fiscal_payload', sa.JSON(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('validation_warnings', sa.JSON(), nullable=True),
    sa.Column('access_key', sa.String(length=44), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('deletion_reason', sa.Text(), nullable=True),
    sa.Column('deletion_mode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['duimp_snapshot_id'], ['duimp_snapshots.id'], ),
    sa.ForeignKeyConstraint(['import_process_id'], ['import_processes.id'], ),
    sa.ForeignKeyConstraint(['importer_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['planned_document_id'], ['nfe_planned_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nfe_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfe_drafts_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_drafts_deleted_by_user_id'), ['deleted_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_drafts_duimp_snapshot_id'), ['duimp_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_drafts_import_process_id'), ['import_process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_drafts_importer_id'), ['importer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_drafts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_drafts_planned_document_id'), ['planned_document_id'], unique=False)

    op.create_table('nfe_planned_document_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_plan_id', sa.UUID(), nullable=False),
    sa.Column('planned_document_id', sa.UUID(), nullable=False),
    sa.Column('duimp_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('item_classification_id', sa.UUID(), nullable=True),
    sa.Column('duimp_item_number', sa.String(length=30), nullable=False),
    sa.Column('exporter_key', sa.String(length=255), nullable=False),
    sa.Column('exporter_code', sa.String(length=100), nullable=True),
    sa.Column('import_purpose', sa.String(length=30), nullable=False),
    sa.Column('cfop', sa.String(length=4), nullable=False),
    sa.Column('customs_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allocated_shared_costs', sa.JSON(), nullable=False),
    sa.Column('raw_source_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_plan_id'], ['nfe_document_plans.id'], ),
    sa.ForeignKeyConstraint(['duimp_snapshot_id'], ['duimp_snapshots.id'], ),
    sa.ForeignKeyConstraint(['item_classification_id'], ['nfe_item_classifications.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['planned_document_id'], ['nfe_planned_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_plan_id', 'duimp_item_number', name='uq_nfe_planned_document_item_plan_item')
    )
    with op.batch_alter_table('nfe_planned_document_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfe_planned_document_items_document_plan_id'), ['document_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_planned_document_items_duimp_snapshot_id'), ['duimp_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_planned_document_items_import_purpose'), ['import_purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_planned_document_items_item_classification_id'), ['item_classification_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_planned_document_items_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_planned_document_items_planned_document_id'), ['planned_document_id'], unique=False)

    op.create_table('nfe_draft_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nfe_draft_id', sa.UUID(), nullable=False),
    sa.Column('item_number', sa.Integer(), nullable=False),
    sa.Column('duimp_item_number', sa.String(length=30), nullable=True),
    sa.Column('product_code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('ncm', sa.String(length=8), nullable=False),
    sa.Column('cfop', sa.String(length=4), nullable=False),
    sa.Column('cest', sa.String(length=10), nullable=True),
    sa.Column('commercial_unit', sa.String(length=20), nullable=False),
    sa.Column('commercial_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('commercial_unit_value', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('taxable_unit', sa.String(length=20), nullable=False),
    sa.Column('taxable_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('taxable_unit_value', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('product_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('freight_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('insurance_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('import_payload', sa.JSON(), nullable=True),
    sa.Column('tax_payload', sa.JSON(), nullable=True),
    sa.Column('import_purpose', sa.String(length=30), nullable=True),
    sa.Column('tax_rule_id', sa.UUID(), nullable=True),
    sa.Column('item_classification_id', sa.UUID(), nullable=True),
    sa.Column('raw_source_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_classification_id'], ['nfe_item_classifications.id'], ),
    sa.ForeignKeyConstraint(['nfe_draft_id'], ['nfe_drafts.id'], ),
    sa.ForeignKeyConstraint(['tax_rule_id'], ['client_import_tax_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nfe_draft_id', 'item_number', name='uq_nfe_draft_item_number')
    )
    with op.batch_alter_table('nfe_draft_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfe_draft_items_import_purpose'), ['import_purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_draft_items_item_classification_id'), ['item_classification_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_draft_items_nfe_draft_id'), ['nfe_draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_draft_items_tax_rule_id'), ['tax_rule_id'], unique=False)

    op.create_table('nfe_issuances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('import_process_id', sa.UUID(), nullable=False),
    sa.Column('nfe_draft_id', sa.UUID(), nullable=False),
    sa.Column('importer_id', sa.UUID(), nullable=False),
    sa.Column('certificate_id', sa.UUID(), nullable=True),
    sa.Column('environment', sa.Enum('homologation', 'production', name='nfe_issuance_environment', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=2), nullable=False),
    sa.Column('series', sa.String(length=3), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('access_key', sa.String(length=44), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('sefaz_authorizer', sa.String(length=30), nullable=True),
    sa.Column('receipt_number', sa.String(length=80), nullable=True),
    sa.Column('protocol_number', sa.String(length=80), nullable=True),
    sa.Column('rejection_code', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'validated', 'xml_generated', 'xsd_validated', 'validation_failed', 'signed', 'submission_pending', 'submitted', 'processing', 'authorized', 'rejected', 'denied', 'cancellation_pending', 'cancelled', 'failed')", name='ck_nfe_issuance_status'),
    sa.CheckConstraint('lock_version >= 0', name='ck_nfe_issuance_lock_version'),
    sa.ForeignKeyConstraint(['certificate_id'], ['fiscal_certificates.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['import_process_id'], ['import_processes.id'], ),
    sa.ForeignKeyConstraint(['importer_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['nfe_draft_id'], ['nfe_drafts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_nfe_issuance_org_idempotency'),
    sa.UniqueConstraint('organization_id', 'importer_id', 'environment', 'model', 'series', 'number', name='uq_nfe_issuance_fiscal_number')
    )
    with op.batch_alter_table('nfe_issuances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfe_issuances_access_key'), ['access_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_nfe_issuances_certificate_id'), ['certificate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_issuances_import_process_id'), ['import_process_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_issuances_importer_id'), ['importer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_issuances_nfe_draft_id'), ['nfe_draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_issuances_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_issuances_protocol_number'), ['protocol_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_issuances_receipt_number'), ['receipt_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_issuances_status'), ['status'], unique=False)

    op.create_table('nfe_xml_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nfe_draft_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('xml_type', sa.Enum('unsigned', 'signed', 'authorized', 'cancelled_event', 'correction_letter_event', name='nfe_xml_type', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('xml_content', sa.Text(), nullable=False),
    sa.Column('xsd_valid', sa.Boolean(), nullable=True),
    sa.Column('xsd_errors', sa.JSON(), nullable=True),
    sa.Column('access_key', sa.String(length=44), nullable=True),
    sa.Column('protocol_number', sa.String(length=80), nullable=True),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nfe_draft_id'], ['nfe_drafts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nfe_draft_id', 'version_number', 'xml_type', name='uq_nfe_xml_version')
    )
    with op.batch_alter_table('nfe_xml_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfe_xml_versions_generated_by_user_id'), ['generated_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_xml_versions_nfe_draft_id'), ['nfe_draft_id'], unique=False)

    op.create_table('nfe_issuance_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nfe_issuance_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('operation', sa.Enum('xsd_validation', 'signature', 'service_status', 'authorization', 'receipt_query', 'protocol_query', 'cancellation', name='nfe_attempt_operation', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('status', sa.Enum('started', 'succeeded', 'failed', 'timed_out', 'unknown', name='nfe_attempt_status', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('request_checksum', sa.String(length=64), nullable=True),
    sa.Column('response_checksum', sa.String(length=64), nullable=True),
    sa.Column('response_code', sa.String(length=30), nullable=True),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('receipt_number', sa.String(length=80), nullable=True),
    sa.Column('protocol_number', sa.String(length=80), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('attempt_number > 0', name='ck_nfe_attempt_positive'),
    sa.ForeignKeyConstraint(['nfe_issuance_id'], ['nfe_issuances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nfe_issuance_id', 'operation', 'attempt_number', name='uq_nfe_attempt_operation_number')
    )
    with op.batch_alter_table('nfe_issuance_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfe_issuance_attempts_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_issuance_attempts_nfe_issuance_id'), ['nfe_issuance_id'], unique=False)

    op.create_table('nfe_issuance_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nfe_issuance_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=40), nullable=False),
    sa.Column('current_status', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nfe_issuance_id'], ['nfe_issuances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nfe_issuance_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfe_issuance_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_issuance_events_nfe_issuance_id'), ['nfe_issuance_id'], unique=False)

    op.create_table('nfe_protocols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nfe_issuance_id', sa.UUID(), nullable=False),
    sa.Column('protocol_type', sa.Enum('authorization', 'cancellation', name='nfe_protocol_type', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('event_sequence', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=20), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('protocol_number', sa.String(length=80), nullable=True),
    sa.Column('response_xml', sa.Text(), nullable=False),
    sa.Column('response_checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('event_sequence > 0', name='ck_nfe_protocol_sequence'),
    sa.ForeignKeyConstraint(['nfe_issuance_id'], ['nfe_issuances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nfe_issuance_id', 'protocol_type', 'event_sequence', name='uq_nfe_protocol_type_sequence')
    )
    with op.batch_alter_table('nfe_protocols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfe_protocols_nfe_issuance_id'), ['nfe_issuance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfe_protocols_protocol_number'), ['protocol_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfe_protocols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfe_protocols_protocol_number'))
        batch_op.drop_index(batch_op.f('ix_nfe_protocols_nfe_issuance_id'))

    op.drop_table('nfe_protocols')
    with op.batch_alter_table('nfe_issuance_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfe_issuance_events_nfe_issuance_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_issuance_events_created_at'))

    op.drop_table('nfe_issuance_events')
    with op.batch_alter_table('nfe_issuance_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfe_issuance_attempts_nfe_issuance_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_issuance_attempts_correlation_id'))

    op.drop_table('nfe_issuance_attempts')
    with op.batch_alter_table('nfe_xml_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfe_xml_versions_nfe_draft_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_xml_versions_generated_by_user_id'))

    op.drop_table('nfe_xml_versions')
    with op.batch_alter_table('nfe_issuances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfe_issuances_status'))
        batch_op.drop_index(batch_op.f('ix_nfe_issuances_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_nfe_issuances_protocol_number'))
        batch_op.drop_index(batch_op.f('ix_nfe_issuances_organization_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_issuances_nfe_draft_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_issuances_importer_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_issuances_import_process_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_issuances_certificate_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_issuances_access_key'))

    op.drop_table('nfe_issuances')
    with op.batch_alter_table('nfe_draft_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfe_draft_items_tax_rule_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_draft_items_nfe_draft_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_draft_items_item_classification_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_draft_items_import_purpose'))

    op.drop_table('nfe_draft_items')
    with op.batch_alter_table('nfe_planned_document_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfe_planned_document_items_planned_document_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_planned_document_items_organization_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_planned_document_items_item_classification_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_planned_document_items_import_purpose'))
        batch_op.drop_index(batch_op.f('ix_nfe_planned_document_items_duimp_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_planned_document_items_document_plan_id'))

    op.drop_table('nfe_planned_document_items')
    with op.batch_alter_table('nfe_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfe_drafts_planned_document_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_drafts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_drafts_importer_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_drafts_import_process_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_drafts_duimp_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_drafts_deleted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_drafts_deleted_at'))

    op.drop_table('nfe_drafts')
    with op.batch_alter_table('nfe_planned_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfe_planned_documents_status'))
        batch_op.drop_index(batch_op.f('ix_nfe_planned_documents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_planned_documents_exporter_code'))
        batch_op.drop_index(batch_op.f('ix_nfe_planned_documents_document_plan_id'))

    op.drop_table('nfe_planned_documents')
    with op.batch_alter_table('nfe_item_classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfe_item_classifications_tax_rule_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_item_classifications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_item_classifications_import_purpose'))
        batch_op.drop_index(batch_op.f('ix_nfe_item_classifications_import_process_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_item_classifications_duimp_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_item_classifications_classified_by_user_id'))

    op.drop_table('nfe_item_classifications')
    with op.batch_alter_table('nfe_document_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfe_document_plans_status'))
        batch_op.drop_index(batch_op.f('ix_nfe_document_plans_organization_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_document_plans_import_process_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_document_plans_duimp_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_document_plans_created_by_user_id'))

    op.drop_table('nfe_document_plans')
    with op.batch_alter_table('external_api_request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_api_request_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_external_api_request_logs_import_process_id'))

    op.drop_table('external_api_request_logs')
    with op.batch_alter_table('duimp_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duimp_snapshots_organization_id'))
        batch_op.drop_index(batch_op.f('ix_duimp_snapshots_import_process_id'))
        batch_op.drop_index(batch_op.f('ix_duimp_snapshots_duimp_number'))

    op.drop_table('duimp_snapshots')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('nfe_number_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfe_number_sequences_status'))
        batch_op.drop_index(batch_op.f('ix_nfe_number_sequences_organization_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_number_sequences_environment'))
        batch_op.drop_index(batch_op.f('ix_nfe_number_sequences_client_id'))

    op.drop_table('nfe_number_sequences')
    with op.batch_alter_table('import_processes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_processes_reference_code'))
        batch_op.drop_index(batch_op.f('ix_import_processes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_import_processes_importer_id'))
        batch_op.drop_index(batch_op.f('ix_import_processes_duimp_number'))
        batch_op.drop_index(batch_op.f('ix_import_processes_created_by_user_id'))

    op.drop_table('import_processes')
    with op.batch_alter_table('fiscal_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fiscal_certificates_valid_until'))
        batch_op.drop_index(batch_op.f('ix_fiscal_certificates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_fiscal_certificates_issuer_cnpj'))
        batch_op.drop_index(batch_op.f('ix_fiscal_certificates_is_active'))
        batch_op.drop_index(batch_op.f('ix_fiscal_certificates_client_id'))

    op.drop_table('fiscal_certificates')
    with op.batch_alter_table('external_provider_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_provider_connections_organization_id'))
        batch_op.drop_index(batch_op.f('ix_external_provider_connections_importer_id'))

    op.drop_table('external_provider_connections')
    with op.batch_alter_table('client_import_tax_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_import_tax_rules_organization_id'))
        batch_op.drop_index(batch_op.f('ix_client_import_tax_rules_ncm_pattern'))
        batch_op.drop_index(batch_op.f('ix_client_import_tax_rules_issuer_state'))
        batch_op.drop_index(batch_op.f('ix_client_import_tax_rules_import_purpose'))
        batch_op.drop_index(batch_op.f('ix_client_import_tax_rules_import_modality'))
        batch_op.drop_index(batch_op.f('ix_client_import_tax_rules_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_import_tax_rules_client_id'))
        batch_op.drop_index(batch_op.f('ix_client_import_tax_rules_active'))

    op.drop_table('client_import_tax_rules')
    with op.batch_alter_table('client_fiscal_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_fiscal_profiles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_client_fiscal_profiles_client_id'))

    op.drop_table('client_fiscal_profiles')
    with op.batch_alter_table('client_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_client_contacts_client_id'))

    op.drop_table('client_contacts')
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_profiles_user_id'))

    op.drop_table('admin_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('nfe_carriers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfe_carriers_trade_name'))
        batch_op.drop_index(batch_op.f('ix_nfe_carriers_tax_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_carriers_state'))
        batch_op.drop_index(batch_op.f('ix_nfe_carriers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_nfe_carriers_municipality_code'))
        batch_op.drop_index(batch_op.f('ix_nfe_carriers_legal_name'))
        batch_op.drop_index(batch_op.f('ix_nfe_carriers_active'))

    op.drop_table('nfe_carriers')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_razao_social'))
        batch_op.drop_index(batch_op.f('ix_clients_organization_id'))
        batch_op.drop_index(batch_op.f('ix_clients_cnpj'))

    op.drop_table('clients')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_nome'))
        batch_op.drop_index(batch_op.f('ix_organizations_cnpj'))

    op.drop_table('organizations')
    with op.batch_alter_table('fiscal_municipalities', schema=None) as batch_op:
        batch_op.drop_index('ix_fiscal_municipalities_state_name')
        batch_op.drop_index(batch_op.f('ix_fiscal_municipalities_state'))
        batch_op.drop_index(batch_op.f('ix_fiscal_municipalities_name'))
        batch_op.drop_index(batch_op.f('ix_fiscal_municipalities_active'))

    op.drop_table('fiscal_municipalities')
    with op.batch_alter_table('fiscal_countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fiscal_countries_valid_until'))
        batch_op.drop_index(batch_op.f('ix_fiscal_countries_valid_from'))
        batch_op.drop_index(batch_op.f('ix_fiscal_countries_name'))
        batch_op.drop_index(batch_op.f('ix_fiscal_countries_iso_alpha_3'))
        batch_op.drop_index(batch_op.f('ix_fiscal_countries_iso_alpha_2'))
        batch_op.drop_index('ix_fiscal_countries_active_validity')
        batch_op.drop_index(batch_op.f('ix_fiscal_countries_active'))

    op.drop_table('fiscal_countries')
    # ### end Alembic commands ###
